name: android-release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Node
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Gradle cache
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      # install deps
      - run: npm ci

      # 生成 android 工程
      - run: npx expo prebuild --platform android --non-interactive

      # build apk
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      # copy apk
      - name: Prepare APK
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          cp android/app/build/outputs/apk/release/app-release.apk v$VERSION.apk

      # release
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: v${{ env.VERSION }}.apk
